services:
  - type: web
    name: laravel-app
    env: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    autoDeploy: true
    buildCommand: ""
    startCommand: "php artisan migrate --force && php-fpm"
